import type { Encounter, SignupDocument } from './types.js';

export const mockEncounters: Encounter[] = [
  { id: 'FRU', name: 'Futures Rewritten (Ultimate)', shortName: 'FRU' },
  { id: 'TOP', name: 'The Omega Protocol (Ultimate)', shortName: 'TOP' },
  { id: 'DSR', name: "Dragonsong's Reprise (Ultimate)", shortName: 'DSR' },
  { id: 'TEA', name: 'The Epic of Alexander (Ultimate)', shortName: 'TEA' },
  { id: 'UWU', name: "The Weapon's Refrain (Ultimate)", shortName: 'UWU' },
  {
    id: 'UCOB',
    name: 'The Unending Coil of Bahamut (Ultimate)',
    shortName: 'UCOB',
  },
];

export const mockSignups: SignupDocument[] = [
  {
    id: '1',
    characterName: 'Warrior Light',
    world: 'Gilgamesh',
    encounter: 'FRU',
    partyType: 'Prog',
    role: 'Tank',
    job: 'Paladin',
    progPoint: 'P2 Light Rampant',
    availability: ['Tuesday 8PM EST', 'Thursday 8PM EST'],
    discordId: '123456789',
    status: 'approved',
    lastUpdated: new Date('2024-01-15'),
    schedulingStatus: 'unscheduled',
    squad: 'Sex Gods 3000',
  },
  {
    id: '2',
    characterName: 'Astral Healer',
    world: 'Leviathan',
    encounter: 'FRU',
    partyType: 'Clear',
    role: 'Healer',
    job: 'White Mage',
    progPoint: 'P5 Fulgent Blade 1 (Exalines 1)',
    availability: ['Monday 7PM EST', 'Wednesday 7PM EST', 'Friday 7PM EST'],
    discordId: '987654321',
    status: 'approved',
    lastUpdated: new Date('2024-01-14'),
    schedulingStatus: 'scheduled',
    squad: 'Space Travelers',
  },
  {
    id: '3',
    characterName: 'Aether Striker',
    world: 'Sargatanas',
    encounter: 'FRU',
    partyType: 'Prog',
    role: 'DPS',
    job: 'Dragoon',
    progPoint: 'P2 Light Rampant',
    availability: ['Thursday 9PM EST', 'Saturday 8PM EST'],
    discordId: '456789123',
    status: 'approved',
    lastUpdated: new Date('2024-01-13'),
    schedulingStatus: 'unscheduled',
    squad: null,
  },
  {
    id: '4',
    characterName: 'Crystal Guardian',
    world: 'Adamantoise',
    encounter: 'FRU',
    partyType: 'Clear',
    role: 'Tank',
    job: 'Dark Knight',
    progPoint: 'P5 Fulgent Blade 1 (Exalines 1)',
    availability: ['Monday 8PM EST', 'Tuesday 8PM EST', 'Thursday 8PM EST'],
    discordId: '789123456',
    status: 'approved',
    lastUpdated: new Date('2024-01-12'),
    schedulingStatus: 'confirmed',
    squad: 'Sex Gods 3000',
  },
  {
    id: '5',
    characterName: 'Void Caster',
    world: 'Cactuar',
    encounter: 'FRU',
    partyType: 'Prog',
    role: 'DPS',
    job: 'Black Mage',
    progPoint: 'P2 Light Rampant',
    availability: ['Wednesday 9PM EST', 'Friday 9PM EST'],
    discordId: '321654987',
    status: 'approved',
    lastUpdated: new Date('2024-01-11'),
    schedulingStatus: 'unscheduled',
    squad: 'Space Travelers',
  },
  {
    id: '6',
    characterName: 'Divine Scholar',
    world: 'Faerie',
    encounter: 'FRU',
    partyType: 'Clear',
    role: 'Healer',
    job: 'Scholar',
    progPoint: 'P5 Fulgent Blade 1 (Exalines 1)',
    availability: ['Tuesday 7PM EST', 'Thursday 7PM EST', 'Sunday 7PM EST'],
    discordId: '654987321',
    status: 'approved',
    lastUpdated: new Date('2024-01-10'),
    schedulingStatus: 'scheduled',
    squad: null,
  },
  {
    id: '7',
    characterName: 'Storm Breaker',
    world: 'Jenova',
    encounter: 'FRU',
    partyType: 'Prog',
    role: 'DPS',
    job: 'Samurai',
    progPoint: 'P2 Light Rampant',
    availability: ['Monday 9PM EST', 'Wednesday 9PM EST', 'Saturday 8PM EST'],
    discordId: '147258369',
    status: 'approved',
    lastUpdated: new Date('2024-01-09'),
    schedulingStatus: 'unscheduled',
    squad: 'Sex Gods 3000',
  },
  {
    id: '8',
    characterName: 'Lunar Sage',
    world: 'Midgardsormr',
    encounter: 'FRU',
    partyType: 'Clear',
    role: 'Healer',
    job: 'Sage',
    progPoint: 'P5 Fulgent Blade 1 (Exalines 1)',
    availability: ['Friday 8PM EST', 'Saturday 8PM EST', 'Sunday 8PM EST'],
    discordId: '963852741',
    status: 'approved',
    lastUpdated: new Date('2024-01-08'),
    schedulingStatus: 'confirmed',
    squad: 'Space Travelers',
  },
  {
    id: '9',
    characterName: 'Iron Defender',
    world: 'Siren',
    encounter: 'TOP',
    partyType: 'Prog',
    role: 'Tank',
    job: 'Gunbreaker',
    progPoint: 'P3 Hello World',
    availability: ['Tuesday 9PM EST', 'Thursday 9PM EST'],
    discordId: '852741963',
    status: 'approved',
    lastUpdated: new Date('2024-01-07'),
    schedulingStatus: 'unscheduled',
    squad: null,
  },
  {
    id: '10',
    characterName: 'Phoenix Rising',
    world: 'Zalera',
    encounter: 'TOP',
    partyType: 'Clear',
    role: 'DPS',
    job: 'Summoner',
    progPoint: 'P6 Alpha Omega',
    availability: ['Monday 8PM EST', 'Friday 8PM EST'],
    discordId: '741963852',
    status: 'approved',
    lastUpdated: new Date('2024-01-06'),
    schedulingStatus: 'scheduled',
    squad: 'Sex Gods 3000',
  },
  {
    id: '11',
    characterName: 'Mystic Dancer',
    world: 'Gilgamesh',
    encounter: 'DSR',
    partyType: 'Prog',
    role: 'DPS',
    job: 'Dancer',
    progPoint: 'P5 Death of the Heavens',
    availability: ['Wednesday 8PM EST', 'Saturday 9PM EST'],
    discordId: '159753486',
    status: 'approved',
    lastUpdated: new Date('2024-01-05'),
    schedulingStatus: 'unscheduled',
    squad: 'Space Travelers',
  },
  {
    id: '12',
    characterName: 'Radiant Priest',
    world: 'Leviathan',
    encounter: 'DSR',
    partyType: 'Clear',
    role: 'Healer',
    job: 'Astrologian',
    progPoint: 'P7 Dragon-king Thordan',
    availability: ['Thursday 7PM EST', 'Sunday 7PM EST'],
    discordId: '486159753',
    status: 'approved',
    lastUpdated: new Date('2024-01-04'),
    schedulingStatus: 'confirmed',
    squad: null,
  },
];
