coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  require_changes: true

codecov:
  require_ci_to_pass: false

ignore:
  - apps/discord-bot/src/slash-commands/**/*-command.ts # Ignore call slash command builder commands from coverage
