coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  require_changes: true

codecov:
  require_ci_to_pass: false
