# fly.toml app configuration file generated for ulti-project-bot on 2024-01-25T10:24:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ulti-project-bot'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  # Disable these when ready to go live since they'll shutdown the machine if its idle
  auto_stop_machines = true 
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  GCP_PROJECT_ID = "ulti-project-407621"
