name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref || '', 'release-please--') }}
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm graphql:codegen
        env:
          FFLOGS_API_ACCESS_TOKEN: ${{ secrets.FFLOGS_API_ACCESS_TOKEN }}
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm lint:ci
      - run: pnpm test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          files: ./coverage/coverage-final.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
