name: CI
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm graphql:codegen
        env:
          FFLOGS_API_ACCESS_TOKEN: ${{ secrets.FFLOGS_API_ACCESS_TOKEN }}
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm lint:ci
      - run: pnpm test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: ./coverage/coverage-final.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
