name: Fly Deploy and Publish Release To Discord
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4
      - uses: superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # master
      # build and upload sourcemaps before we deploy this image
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm sentry:sourcemaps
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  publish-release-to-discord:
    name: Publish Release To Discord
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: ssilve1989/github-releases-to-discord-action
          token: ${{ secrets.ULTI_PROJECT_PAT }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          version: latest
      - run: pnpm install
      - run: pnpm build
      - name: Run Publish Release
        uses: ./
        with:
          webhook-url: ${{ secrets.DISCORD_RELEASES_WEBHOOK_URL }}
