name: Publish Release To Discord
on:
  release:
    types: [published, edited]

jobs:
  publish-release-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action repository
        uses: actions/checkout@v4
        with:
          repository: ssilve1989/github-releases-to-discord-action
          token: ${{ secrets.DISCORD_RELEASES_TOKEN }}
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4
        with:
          # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions.
          # If node-version and node-version-file are both provided the action will use version from node-version.
          node-version-file: ".nvmrc"

          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          # Package manager should be pre-installed
          # Default: ''
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - name: Run Publish Release
        uses: ./
        with:
          webhook-url: ${{ secrets.DISCORD_RELEASES_WEBHOOK_URL }}
